#networks:
#  kafka-net:
#    name: kafka-net
#    driver: bridge

services:

  postgres:
    image: postgres:latest
    container_name: crypto-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      PGUSER: root
    ports:
      - '35432:5432'

#  kafka:
#    image: apache/kafka:latest
#    container_name: crypto-kafka
#    hostname: kafka
#    environment:
#      CLUSTER_ID: S-Vgn-LcRMOnFr3K_SXIOQ
#      KAFKA_NODE_ID: 1
#      KAFKA_PROCESS_ROLES: broker,controller
#      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#      KAFKA_LISTENERS: INTERNAL://localhost:29092,CONTROLLER://localhost:29093,EXTERNAL://0.0.0.0:9092,UI://0.0.0.0:9093
#      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092,UI://kafka:9093
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,UI:PLAINTEXT
#      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:29093
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#      KAFKA_NUM_PARTITIONS: 1
#      KAFKA_JMX_OPTS: "
#        -Dcom.sun.management.jmxremote
#        -Dcom.sun.management.jmxremote.port=9997
#        -Dcom.sun.management.jmxremote.authenticate=false
#        -Dcom.sun.management.jmxremote.ssl=false
#      "
#    ports:
#      - '9092:9092'
#      - '9093:9093'
#      - '9997:9997'

#  kafka-ui:
#    image: provectuslabs/kafka-ui:latest
#    container_name: crypto-kafka-ui
#    depends_on:
#      - kafka
#    environment:
#      KAFKA_CLUSTERS_0_NAME: local
#      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
#      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
#      DYNAMIC_CONFIG_ENABLED: 'true'
#    ports:
#      - '8280:8080'

  nats:
    container_name: crypto-nats
    image: nats:2.11.3-alpine3.21
    command: "--config /jetstream.config"
    ports:
      - '4223:4223'
    volumes:
      - ./jetstream.config:/jetstream.config
#      - ./persistent-data/server-n1/:/data/jetstream